name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.3

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Build and push docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            caioeduardolobo/desafiopicpay:${{ github.run_number }}
            caioeduardolobo/desafiopicpay:latest

  CD:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull caioeduardolobo/desafiopicpay:latest

      - name: Run docker container
        run: docker run -d -p 8080:8080 --name desafiopicpay caioeduardolobo/desafiopicpay